#!/usr/bin/env python3
"""
Example Web UI Configuration
This file is auto-generated by the web dashboard when you configure detection boxes.

ConfigManager will auto-detect this file and load it as a visual prompt config.
"""

# Reference image path (latest detection screenshot)
refer_image = r"/home/zarred/dev/laser-monitor/output/screenshots/detection_20251112_120000.jpg"

# Visual prompt bounding boxes (normalized coordinates: x1, y1, x2, y2)
# Example: Two detection boxes for monitoring two laser indicators
visual_prompts = [
    [0.75, 0.41, 0.76, 0.47],  # Box 1: Top-right indicator
    [0.18, 0.46, 0.19, 0.48]   # Box 2: Left side indicator
]

# Image dimensions (for reference)
image_dimensions = {
    "width": 1920,
    "height": 1080
}

# Metadata
metadata = {
    "created_with": "web_ui_dashboard",
    "num_prompts": 2,
    "last_modified": "2025-11-12T12:00:00"
}
