#!/usr/bin/env python3
"""
Visual Prompts Configuration
Generated by Laser Monitor Web UI
Auto-loaded by ConfigManager when monitoring starts

This file follows the same format as configs generated by visual_prompt_selector.py
and is compatible with create_config_with_visual_prompts().
"""

# Reference image path (latest detection screenshot)
refer_image = r"/home/hilton/laser-monitor/output/screenshots/detection_20260224_190903.jpg"

# Visual prompt bounding boxes (normalized coordinates: x1, y1, x2, y2)
visual_prompts = [[0.6302083333333334, 0.41, 0.6428125, 0.47], [0.03416666666666665, 0.4322222222222222, 0.044166666666666674, 0.46148148148148144]]

# Image dimensions (for reference)
image_dimensions = {
    "width": 1920,
    "height": 1080
}

# Metadata
metadata = {
    "created_with": "web_ui_dashboard",
    "num_prompts": 2,
    "last_modified": "2026-03-02T19:11:00.212244"
}
