#!/usr/bin/env python3
"""
Visual Prompts Configuration
Generated by Laser Monitor Web UI
Auto-loaded by ConfigManager when monitoring starts

This file follows the same format as configs generated by visual_prompt_selector.py
and is compatible with create_config_with_visual_prompts().
"""

# Reference image path (latest detection screenshot)
refer_image = r"/home/hilton/laser-monitor/output/screenshots/detection_20260612_145905.jpg"

# Visual prompt bounding boxes (normalized coordinates: x1, y1, x2, y2)
visual_prompts = [[0.6234375, 0.412962962962963, 0.64375, 0.45925925925925926], [0.015625, 0.4074074074074074, 0.057291666666666664, 0.5]]

# Image dimensions (for reference)
image_dimensions = {
    "width": 1920,
    "height": 1080
}

# Metadata
metadata = {
    "created_with": "web_ui_dashboard",
    "num_prompts": 2,
    "last_modified": "2026-06-12T14:59:48.832699"
}
