#!/usr/bin/env python3
"""
Visual Prompts Configuration
Generated by visual_prompt_selector.py

Usage:
    from config.config import default_config, create_config_with_visual_prompts
    config = create_config_with_visual_prompts(default_config, "tests/test1.config.py")
"""

# Reference image path
refer_image = r"/home/zarred/dev/laser-monitor/tests/test1.jpg"

# Visual prompt bounding boxes (normalized coordinates: x1, y1, x2, y2)
visual_prompts = [[0.646875, 0.41388888888888886, 0.6598958333333333, 0.4703703703703704], [0.05572916666666667, 0.44814814814814813, 0.0625, 0.4759259259259259]]

# Image dimensions (for reference)
image_dimensions = {
    "width": 1920,
    "height": 1080
}

# Metadata
metadata = {
    "created_with": "visual_prompt_selector.py",
    "num_prompts": 2,
    "original_image": r"/home/zarred/dev/laser-monitor/tests/test1.jpg"
}
