#!/usr/bin/env python3
"""
Visual Prompts Configuration
Generated by visual_prompt_selector.py

Usage:
    from config.config import default_config, create_config_with_visual_prompts
    config = create_config_with_visual_prompts(default_config, "images/test.config.py")
"""

# Reference image path
refer_image = r"/home/hilton/laser-monitor/images/test.jpg"

# Visual prompt bounding boxes (normalized coordinates: x1, y1, x2, y2)
visual_prompts = [[0.6473958333333333, 0.4185185185185185, 0.6588541666666666, 0.46574074074074073], [0.05677083333333333, 0.44814814814814813, 0.0625, 0.47314814814814815]]

# Image dimensions (for reference)
image_dimensions = {
    "width": 1920,
    "height": 1080
}

# Metadata
metadata = {
    "created_with": "visual_prompt_selector.py",
    "num_prompts": 2,
    "original_image": r"/home/zarred/dev/laser_monitor/images/test.jpg"
}
