#!/usr/bin/env python3
"""
Visual Prompts Configuration
Generated by visual_prompt_selector.py

Usage:
    from config.config import default_config, create_config_with_visual_prompts
    config = create_config_with_visual_prompts(default_config, "images/test.config.py")
"""

# Reference image path
refer_image = r"output/latest_raw.jpg"

# Visual prompt bounding boxes (normalized coordinates: x1, y1, x2, y2)
# Recommissioned against the unannotated persistent-camera frame on 2026-07-20.
visual_prompts = [[0.6270833333333333, 0.4148148148148148, 0.6364583333333333, 0.47129629629629627], [0.025, 0.4444444444444444, 0.0375, 0.4777777777777778]]

# Image dimensions (for reference)
image_dimensions = {
    "width": 1920,
    "height": 1080
}

# Metadata
metadata = {
    "created_with": "visual_prompt_selector.py",
    "num_prompts": 2,
    "original_image": r"/home/zarred/dev/laser_monitor/images/test.jpg"
}
