#!/usr/bin/env python3
"""
Visual Prompts Configuration
Generated by visual_prompt_selector.py

Usage:
    from config.config import default_config, create_config_with_visual_prompts
    config = create_config_with_visual_prompts(default_config, "images/test.config.py")
"""

# Reference image path
refer_image = r"/home/hilton/git-repo/images/test.jpg"

# Visual prompt bounding boxes (normalized coordinates: x1, y1, x2, y2)
visual_prompts = [[0.7494791666666667, 0.41388888888888886, 0.7640625, 0.4703703703703704], [0.18333333333333332, 0.4583333333333333, 0.190625, 0.4842592592592593]]

# Image dimensions (for reference)
image_dimensions = {
    "width": 1920,
    "height": 1080
}

# Metadata
metadata = {
    "created_with": "visual_prompt_selector.py",
    "num_prompts": 2,
    "original_image": r"/home/zarred/dev/laser_monitor/images/test.jpg"
}
