#!/usr/bin/env python3
"""
Visual Prompts Configuration
Generated by visual_prompt_selector.py

Usage:
    from config.config import default_config, create_config_with_visual_prompts
    config = create_config_with_visual_prompts(default_config, "images/test.config.py")
"""

# Reference image path
refer_image = r"/home/zarred/dev/laser_monitor/images/test.jpg"

# Visual prompt bounding boxes (normalized coordinates: x1, y1, x2, y2)
visual_prompts = [[0.7765625, 0.4111111111111111, 0.79375, 0.47129629629629627], [0.21302083333333333, 0.45740740740740743, 0.21979166666666666, 0.4842592592592593]]

# Image dimensions (for reference)
image_dimensions = {
    "width": 1920,
    "height": 1080
}

# Metadata
metadata = {
    "created_with": "visual_prompt_selector.py",
    "num_prompts": 2,
    "original_image": r"/home/zarred/dev/laser_monitor/images/test.jpg"
}
